In [1]:
# libraries
import pandas as pd
import numpy as np

In [2]:
# get pandas version
pd.__version__

'1.4.3'

In [3]:
# read data from file
housing = pd.read_csv('./housing.csv')
housing.head(5)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [4]:
len(housing.columns)

10

In [5]:
# data info
housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [6]:
# unique values in ocean proximity 
housing['ocean_proximity'].nunique()

5

In [7]:
# average value of median_house_value

housing[housing['ocean_proximity'] == 'NEAR BAY']["median_house_value"].mean().round(0)

259212.0

In [ ]:
# remove nan values
housing.dropna(inplace = True)

# new average after nan values removed
housing[housing['ocean_proximity'] == 'NEAR BAY']["median_house_value"].mean().round(0)

In [8]:
# question 7

island = housing['ocean_proximity'] == "ISLAND"

island_only = housing[island]

island_only_subset =  island_only[['housing_median_age','total_bedrooms','total_rooms']]



In [9]:
island_only_subset

housing_median_age  total_bedrooms  total_rooms
8314                27.0           521.0       1675.0
8315                52.0           591.0       2359.0
8316                52.0           512.0       2127.0
8317                52.0           264.0        996.0
8318                29.0           214.0        716.0

In [10]:
# tranform subset into numpy array
X = island_only_subset.values
X

array([[  27.,  521., 1675.],
       [  52.,  591., 2359.],
       [  52.,  512., 2127.],
       [  52.,  264.,  996.],
       [  29.,  214.,  716.]])

In [14]:
# multiplication of X and its tranpose
XTX = X.T.dot(X)
XTX

array([[9.6820000e+03, 9.1357000e+04, 3.5105300e+05],
       [9.1357000e+04, 9.9835800e+05, 3.7720360e+06],
       [3.5105300e+05, 3.7720360e+06, 1.4399307e+07]])

In [15]:
# inverse of XTX
XTX_inverse = np.linalg.inv(XTX)
XTX_inverse

array([[ 9.19403586e-04,  5.43072261e-05, -3.66412216e-05],
       [ 5.43072261e-05,  1.00891325e-04, -2.77534485e-05],
       [-3.66412216e-05, -2.77534485e-05,  8.23303633e-06]])

In [16]:
# find w 
y = [950, 1300, 800, 1000, 1300]


In [18]:
w = XTX_inverse.dot(X.T).dot(y)

In [19]:
w

array([23.12330961,  5.69922946, -1.48124183])