### Introduction To Numpy Library

In [1]:
# importing numpy  library
import numpy as np 

#### Single Dimimensional Arrays

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10,7)

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [7]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [9]:
a[2] = 10

In [10]:
a

array([ 1,  2, 10,  4,  5,  6])

In [12]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [17]:
np.linspace(0,100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

#### Multidimensional Arrays

In [18]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
md = np.array(
    ([1,2,3],
    [4,5,6],
    [7,8,9])
)

In [25]:
md[1,2]

6

In [27]:
md[0,1] = 100

In [28]:
md

array([[  1, 100,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [37]:
md[1] = [56,34,23]

In [38]:
md

array([[  1, 100,   3],
       [ 56,  34,  23],
       [  7,   8,   9]])

In [36]:
md[:,1]

array([100,  34,   8])

#### Randomly generated arrays

In [45]:
np.random.seed(2)
100 * np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [46]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [49]:
np.random.seed(2)
np.random.randint(low = 0, high = 50, size=(5,4))

array([[40, 15, 45,  8],
       [22, 43, 18, 11],
       [40,  7, 34, 49],
       [31, 11, 21, 47],
       [31, 26, 20, 37]])